version: "3.7"
services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=db
      - MYSQL_USER=helga
      - MYSQL_PASSWORD=diplom
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=helga
      - POSTGRES_PASSWORD=diplom
  NODE:
    build: gate-simulator/
    image: node-app:18.5.0
    ports:
      - '9999:9999'